In [11]:
import pickle
import numpy as np
from sklearn.linear_model import LogisticRegression

In [4]:
with open("../data/amazon_reviews/amazon_4.pickle", "rb") as fr:
    all_data = pickle.load(fr)

lr = LogisticRegression(C=0.1, max_iter=200000)

In [6]:
all_data[0]

(array([[ 0.04075839,  0.05910503,  0.13972619, ..., -0.06301638,
          0.4450332 ,  0.23183767],
        [-0.02973443, -0.03376829,  0.06094901, ..., -0.13512635,
          0.35807544,  0.3044202 ],
        [-0.06972118,  0.03179864, -0.11417986, ...,  0.04598498,
          0.2473178 ,  0.08969769],
        ...,
        [-0.00496966,  0.04295776,  0.04823667, ..., -0.03258032,
          0.40385824,  0.3256419 ],
        [ 0.06021781,  0.00802504,  0.0266686 , ...,  0.102793  ,
          0.29291397,  0.3384165 ],
        [-0.05725368, -0.00675954, -0.21957697, ...,  0.03083247,
          0.36693576,  0.36155334]], dtype=float32),
 array([1, 1, 1, ..., 0, 0, 0]),
 'Home_and_Kitchen.train')

In [8]:
model = lr
x_source = all_data[0][0]
y_source = all_data[0][1]

x_ti = all_data[1][0]
y_ti = all_data[1][1]

model.fit(x_source, y_source)
y_prob_ti = model.predict_proba(x_ti)[:, 0]

In [9]:
y_prob_ti

array([0.92097903, 0.01119405, 0.00728437, ..., 0.91054763, 0.95807208,
       0.27811553])

In [21]:
sorted(y_prob_ti)[1376]

0.9209790288688218

In [24]:
dists_order = np.argsort(y_prob_ti)
dists_rank = np.argsort(dists_order)
dists_rank

array([1376,  118,   79, ..., 1322, 1610,  640])

In [26]:
y_prob_ti[dists_rank > len(dists_rank) - 30]

array([0.99736321, 0.99452938, 0.99640317, 0.99718171, 0.99627051,
       0.99767376, 0.99484895, 0.99635455, 0.99915499, 0.99445269,
       0.99845843, 0.99841683, 0.99748908, 0.99680308, 0.99768305,
       0.996011  , 0.99623673, 0.99472014, 0.99896197, 0.99528275,
       0.99671176, 0.99676131, 0.9963116 , 0.99469409, 0.99423182,
       0.99804318, 0.99448706, 0.99653961, 0.99429368])